import type { NextPage } from "next";
import Head from "next/head";
import _ from "lodash";

// Components
import Header from "../components/header";
import PostTile from "../components/post-tile";
import TextStrip from "../components/text-strip";

// GraphQl
import { request } from "../lib/datocms";
import { HOMEPAGE_QUERY } from "../lib/query";

// Types
import type { HomeType, PostType } from "../types";
import Layout from "../components/layout";
import Container from "../components/container";

export async function getStaticProps() {
  const homeData = await request({
    query: HOMEPAGE_QUERY,
    variables: null,
    preview: false,
  });
  return {
    props: { homeData },
  };
}

const Home: React.FC<HomeType> = ({ homeData }) => {
  const featurePost = homeData.allPosts[4];
  const stripPostTop = homeData.allPosts[5];
  const stripPostBottom = homeData.allPosts[6];

  const categories = homeData.allPosts.map(
    (post: PostType) => post.category.name
  );
  return (
    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    <Layout navItems={_.uniq(categories)}>
      <Container>
        <div className="page-content home">
          <TextStrip
            image={{ src: "/eustace-400.png", alt: "Support Buzzz" }}
            justifyContent="center"
            text="Support <i>Buzz the boy's</i> award winning journalism. <a href='/'>Subscribe today »"
          />

          <div className="grid above-fold">
            <div className="grid-col--thumbnail-posts">
              {homeData.allPosts
                .slice(0, 3)
                .map(
                  ({
                    id,
                    title,
                    category,
                    excerpt,
                    coverImage,
                    author,
                    slug,
                  }: PostType) => {
                    return (
                      <PostTile
                        id={id}
                        tileType="default"
                        slug={slug}
                        key={id}
                        title={title}
                        category={category.name}
                        excerpt={excerpt}
                        coverImage={coverImage}
                        blurUpThumb={coverImage.blurUpThumb}
                        author={author.name}
                      />
                    );
                  }
                )}
            </div>

            <div className="grid-col--featured-posts">
              <PostTile
                id={featurePost.id}
                slug={featurePost.slug}
                tileType="feature"
                title={featurePost.title}
                category={featurePost.category.name}
                excerpt={featurePost.excerpt}
                coverImage={featurePost.coverImage}
                blurUpThumb={featurePost.coverImage.blurUpThumb}
                author={featurePost.author.name}
              />
              <PostTile
                id={stripPostTop.id}
                slug={stripPostTop.slug}
                tileType="strip"
                title={stripPostTop.title}
                category={stripPostTop.category.name}
                excerpt={stripPostTop.excerpt}
                coverImage={stripPostTop.coverImage}
                blurUpThumb={stripPostTop.coverImage.blurUpThumb}
                author={stripPostTop.author.name}
              />
              <PostTile
                id={stripPostBottom.id}
                slug={stripPostBottom.slug}
                tileType="strip"
                title={stripPostBottom.title}
                category={stripPostBottom.category.name}
                excerpt={stripPostBottom.excerpt}
                coverImage={stripPostBottom.coverImage}
                blurUpThumb={stripPostBottom.coverImage.blurUpThumb}
                author={stripPostBottom.author.name}
              />
            </div>

            <div className="grid-col--news-culture">
              <h2 className="title">News & Culture</h2>
              {homeData.allPosts
                .slice(7, 16)
                .map(
                  ({
                    id,
                    title,
                    category,
                    excerpt,
                    coverImage,
                    author,
                    slug,
                  }: PostType) => {
                    return (
                      <PostTile
                        id={id}
                        slug={slug}
                        tileType="mini"
                        key={id}
                        title={title}
                        category={category.name}
                        excerpt={excerpt}
                        coverImage={coverImage}
                        blurUpThumb={coverImage.blurUpThumb}
                        author={author.name}
                      />
                    );
                  }
                )}
            </div>
          </div>
        </div>
      </Container>
    </Layout>
  );
};

export default Home;
